name: Latest blog post workflow
on:
#   schedule: # Run workflow automatically
#     - cron: '0 * * * *' # Runs every hour, on the hour
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the GitHub Actions Workflow page directly
  repository_dispatch:
    types: [generate]

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Pull in github page posts
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://deletefromuser.github.io/index.xml"
          template: <li>$date - <a href="$url" rel="nofollow">$title</a></li>
          date_format: yyyy-mm-dd
          tag_post_pre_newline: true
      - name: Pull in github page articles
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          comment_tag_name: "READ-BOOK-LIST"
          feed_list: "https://deletefromuser.github.io/read/index.xml"
          template: <li>$date - <a href="$url" rel="nofollow">$title</a></li>
          date_format: yyyy-mm-dd
          tag_post_pre_newline: true
#           template: \- $date - [$title]($url)
#           date_format: yyyy-mm-dd
